name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  job:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            vcpkgCommitId: '0591528cbfde14ccfd3900c3fb19aba382c05349'
            vcpkgPackages: 'sqlite3'
          - os: ubuntu-latest
            triplet: x64-linux
            vcpkgCommitId: '0591528cbfde14ccfd3900c3fb19aba382c05349'
            vcpkgPackages: 'sqlite3'
          - os: macos-latest
            triplet: x64-osx
            vcpkgCommitId: '0591528cbfde14ccfd3900c3fb19aba382c05349'
            vcpkgPackages: 'sqlite3'

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - uses: lukka/get-cmake@latest
    - name: dir
      run: find ${{ runner.workspace }}
      if: "!contains( matrix.os, 'windows')"
    - name: dir
      run: gci -recurse ${{ runner.workspace }}
      if: contains( matrix.os, 'windows')
    - name: get-cmake
      uses: lukka/get-cmake@v3.17.2
    - name: Run CMake+Ninja without triplet
      uses: lukka/run-cmake@v2
      id: runcmake
      with:
        cmakeGenerator: 'Ninja'  
        cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
        cmakeListsTxtPath: '${{ github.workspace }}/cmakeliststxt/CMakeLists.txt'
        useVcpkgToolchainFile: true
        buildWithCMakeArgs: '-- -v'
        buildDirectory: '${{ runner.workspace }}/b/ninja/'
