name: C/C++ CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-ubuntu:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: lukka/get-cmake@latest

      - name: dir
        run: find ${{ runner.workspace }}

      - name: get-cmake
        uses: lukka/get-cmake@v3.17.2

      - name: build src
        uses: lukka/run-cmake@v2
        with:
          cmakeGenerator: "Ninja"
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeListsTxtPath: "${{ github.workspace }}/CMakeLists.txt"
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: "-- -v"
          buildDirectory: "${{ runner.workspace }}/build/"

      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - uses: actions/upload-artifact@v2
        with:
          name: winchess-build-${{ steps.slug.outputs.sha8 }}
          path: ${{ runner.workspace }}/build/

      - name: "Get master"
        uses: actions/checkout@v2
        if: github.event_name == 'pull_request'
        with:
          ref: master
          path: "winchess-master"

      - name: dir
        if: github.event_name == 'pull_request'
        run: find ${{ github.workspace  }}/winchess-master/

      - name: Build master
        uses: lukka/run-cmake@v2
        if: github.event_name == 'pull_request'
        with:
          cmakeGenerator: "Ninja"
          cmakeListsOrSettingsJson: "CMakeListsTxtBasic"
          cmakeListsTxtPath: "${{ github.workspace }}/winchess-master/CMakeLists.txt"
          useVcpkgToolchainFile: true
          buildWithCMakeArgs: "-- -v"
          buildDirectory: "${{ runner.workspace }}/master-build/"

      - name: unpack-cutechess
        run: tar xvzf ${{ github.workspace }}/tests/assets/cutechess-cli.tar.gz -C ${{ runner.workspace }}
        if: github.event_name == 'pull_request'

      - name: install-cutechess
        run: echo "::add-path::${{ runner.workspace }}/cutechess-cli"
        if: github.event_name == 'pull_request'

      - name: install cutechess dependencies
        run: |
          sudo apt install libqt5core5a
          sudo strip --remove-section=.note.ABI-tag ${{ runner.workspace }}/cutechess-cli/lib/libQt5Core.so.5
          cd ${{ runner.workspace }}/cutechess-cli/lib

      - name: run-tests
        run: ${{ runner.workspace }}/build/winchess_tests ${{ runner.workspace }}/build/winchess ${{ runner.workspace }}/master-build/winchess
        if: github.event_name == 'pull_request'

      - name: run-cutechess
        run: cutechess-cli -engine cmd=${{ runner.workspace }}/build/winchess name=winchess -engine cmd=${{ runner.workspace }}/master-build/winchess name=winchessmaster -each proto=uci tc=40/2 -rounds 2 -recover -wait 1 -debug -pgnout ${{ runner.workspace }}/play-results.txt
        if: github.event_name == 'pull_request'

      - uses: actions/upload-artifact@v2
        with:
          name: play-results
          path: ${{ runner.workspace }}/play-results.txt
